apiVersion: 1

datasources:
  - name: Prometheus
    uid: bee8fzve0esjkc
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    overwrite: true

  - name: Grafana Pyroscope
    type: grafana-pyroscope-datasource
    url: http://localhost:4040
    jsonData:
      minStep: '15s'
