{
 "title": "API Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "API Observations Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_status_observations", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Climatologique Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_status_climatologique", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Vigilance Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_status_vigilance", "legendFormat": "__auto" }
   ]
  },
  { "title": "API Observations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of Cycles",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "observation_cycle_runs_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Station ID",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "observation_current_station", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg Duration of Cycle (minutes)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(observation_cycle_duration_seconds_sum) / sum(observation_cycle_duration_seconds_count) /60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Duration for a Batch",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "sum(observation_batch_processing_seconds_sum) / sum(observation_batch_processing_seconds_count)",
     "legendFormat": "Average duration"
    }
   ]
  },
  {
   "title": "Stations Processed (Current Cycle)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "observation_stations_processed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fetch status",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 10, "x": 5, "y": 20 },
   "targets": [
    {
     "expr": "sum by(status) (observation_fetch_attempts_total)",
     "legendFormat": "Total ({{status}})"
    }
   ]
  },
  {
   "title": "Station ID for Errors/Quota",
   "type": "table",
   "gridPos": { "h": 19, "w": 9, "x": 15, "y": 20 },
   "targets": [
    {
     "expr": "sum by(station_id, status) (observation_fetch_attempts_total{status!~\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Time for a Single Request",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(observation_fetch_duration_seconds_sum)\r\n/\r\nsum(observation_fetch_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Fetches",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (rate(observation_fetch_attempts_total[5m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Climatologique", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Number of Job Done",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "climatological_job_runs_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Cycles Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(climatological_cycle_duration_seconds_sum) / sum(climatological_cycle_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Batch Proocessing (seconds)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(climatological_batch_duration_seconds_sum) / sum(climatological_batch_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Command Time (second)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(climatological_command_duration_seconds_sum) / avg(climatological_command_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Fetch Time (seconds)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(climatological_csv_fetch_duration_seconds_sum)  / sum(climatological_csv_fetch_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Commands",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(climatological_command_requests_total) by (status)",
     "legendFormat": "Total ({{status}})"
    }
   ]
  },
  {
   "title": "Station Errors",
   "type": "table",
   "gridPos": { "h": 19, "w": 9, "x": 15, "y": 49 },
   "targets": [
    {
     "expr": "sum(climatological_command_requests_total{status!~\"success\"}) by (station, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Commands (per minute)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(climatological_command_requests_total[5m])) by (status) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Feteches",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum (climatological_csv_fetch_total) by(status)",
     "legendFormat": "Total ({{status}})"
    },
    {}
   ]
  },
  {
   "title": "Commands Errors",
   "type": "table",
   "gridPos": { "h": 19, "w": 9, "x": 15, "y": 68 },
   "targets": [
    {
     "expr": "sum(climatological_csv_fetch_total{status!~\"done\"}) by (command_id, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Fetches (per minute)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (rate(climatological_csv_fetch_total[5m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}